# .github/workflows/build_and_push.yml
name: Docker Build & Push

on:
  workflow_call:
    inputs:
      ref:
        description: Git ref to checkout
        required: true
        type: string
    outputs:
      image_tag:
        description: Image tag
        value: ${{ jobs.build-and-push.outputs.image_tag }} # This references the job-level output
    secrets:
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: dimitrisstyl7/juice-shop:latest
    outputs:
      image_tag: ${{ env.IMAGE_TAG }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # get the full history
          ref: ${{ inputs.ref }}

      - name: Build the Docker image
        run: docker build . -f Dockerfile -t ${{ env.IMAGE_TAG }}

      - name: Push the Docker image
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}  # injected securely
        run: |
          # Log in to Docker Hub using STDIN - the token never appears in the command line
          echo "$DOCKERHUB_TOKEN" | docker login -u dimitrisstyl7 --password-stdin

          # Push the image
          docker push ${{ env.IMAGE_TAG }}