name: CI - Secret Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  truffleHog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog Secret Scanning
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true

      - name: Fail if secrets detected
        if: steps.trufflehog.outcome == 'failure'
        run: |
          echo "🚨 Secrets were detected - aborting the workflow."
          exit 1