# .github/workflows/ci.yml
name: CI - Secret Scan → Docker Build & Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  trufflehog:
    uses: ./.github/workflows/trufflehog.yml
    with:
      ref: ${{ github.ref_name }}

  build:
    needs: trufflehog
    if: ${{ needs.trufflehog.outputs.secrets_found == 'false' }}
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}