name: CI - Secret Scan, Docker Build & Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  truffleHog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog Secret Scanning
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
        # scan entire branch
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --results=verified,unknown

#      - name: Fail if secrets detected
#        if: steps.trufflehog.outcome == 'failure'
#        run: |
#          echo "🚨 Secrets were detected - aborting the workflow."
#          exit 1

  build:
    needs: truffleHog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the docker image
        run: docker build . --file Dockerfile --tag dimitrisstyl7/juice-shop:latest

      - name: Push the docker image
        run: |
          docker login -u dimitrisstyl7 -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push dimitrisstyl7/juice-shop:latest