# .github/workflows/snyk.yml
name: Snyk Vulnerabilities Scan

on:
  workflow_call:
    inputs:
      ref:
        description: Git ref to scan
        required: true
        type: string
    secrets:
      SNYK_TOKEN:
        required: true
    outputs:
      vulnerabilities_found:  # This is the output that ci.yml will read
        description: True if vulnerabilities were found
        value: ${{ jobs.scan.outputs.vulnerabilities_found }} # This references the job-level output

jobs:
  scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      vulnerabilities_found: ${{ steps.set_output.outputs.vulnerabilities_found }} # Expose output from this job
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Snyk Vulnerabilities Scanning
        id: snyk
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Set result output
        id: set_output
        run: |
          if [[ "${{ steps.snyk.outcome }}" == "failure" ]]; then
            echo "vulnerabilities_found=true" >> "$GITHUB_OUTPUT"
          else
            echo "vulnerabilities_found=false" >> "$GITHUB_OUTPUT"
          fi