# .github/workflows/trufflehog.yml
name: TruffleHog Secrets Scan

on:
  workflow_call:
    inputs:
      ref:
        description: Git ref to scan
        required: true
        type: string
    outputs:
      secrets_found:  # This is the output that ci.yml will read
        description: True if secrets were found
        value: ${{ jobs.scan.outputs.secrets_found }} # This references the job-level output

jobs:
  scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      secrets_found: ${{ steps.set_output.outputs.secrets_found }} # Expose output from this job
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # get the full history
          ref: ${{ inputs.ref }}

      - name: TruffleHog Secret Scanning
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          base: ""  # scan entire branch
          head: ${{ inputs.ref }}
          extra_args: --results=verified,unknown

      - name: Set result output
        id: set_output
        run: |
          if [[ "${{ steps.trufflehog.outcome }}" == "failure" ]]; then
            echo "secrets_found=true" >> "$GITHUB_OUTPUT"
          else
            echo "secrets_found=false" >> "$GITHUB_OUTPUT"
          fi